### ISSUE TITLE
Não linka com o Python

### ISSUE THREAD

**Issue by LeoFuso** [LeoFuso/cpp_python_integration#1]
Tudo ocorre bem, o `build process` termina sem erros, e no final, uma biblioteca `sqrtlib.so` é criada, de acordo com o esperado.

Porém, quando vou realizar a _linkagem_ com o `Python` ocorre uma `segment fault`. Eu não tenho ideia do porquê isso está acontecendo, e estou avidamente acompanhando esta [página](https://www.boost.org/doc/libs/1_66_0/libs/python/doc/html/article.html) a procura de erros.

Sem sucesso algum.

**Comment by LeoFuso** [comment]
[Documentação](https://www.boost.org/doc/libs/1_66_0/libs/python/doc/html/article.html)

**Comment by LeoFuso** [comment]
Segue o `Stacktrace` apresentado pelo `Python`:

``` python
Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sqrtlib import SquareRoot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/lfuso/Repository/cpp_python_integration/cpp/build/sqrtlib.so: undefined symbol: _ZN10SquareRoot9calculateEd
>>> 
Falha de segmentação (imagem do núcleo gravada)

```

**Comment by calebepb** [comment]
Acho que é visibilidade das classes/objetos envolvidos. Digo isso porque os códigos abaixo funcionam:
* C++ (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)
```
#include <boost/python.hpp>

using namespace boost::python;

class Dummy
{
        public:
                Dummy() {}

                double dummyCalc(const double x)
                {
                        return x;
                }
};


// Defines a python module which will be named "sqrtlib"
BOOST_PYTHON_MODULE (sqrtlib)
{
        /* Defines a SquareRoot class with just one method:
         * @calculate Returns the SquareRoot of a given double
         */
        class_<Dummie> sqrt("Dummie");
        sqrt.def("dummieCalc", &Dummie::dummieCalc);
}
```
* Python 3.6.5
```
from sqrtlib import Dummy
dummy = Dummy()
print(dummy.dummyCalc(4.5))
```

Mas, se eu tento fazer qualquer chamada à classe `SquareRoot`, mesmo usando a classe `Dummy` como wrapper, ele apresenta o mesmo erro: `ImportError: sqrtlib.so: undefined symbol: _ZN10SquareRoot9calculateEd`

**Comment by LeoFuso** [comment]
Certo, baseado nesta sugestão, criarei uma `branch` nova a partir da `dev` com o intuíto de implementar uma outra aplicação em `C++` que servirá como consumidora dessa biblioteca, para ter certeza que os `links` estão funcionando corretamente. 

Usarei este [tópico](https://stackoverflow.com/questions/12573816/what-is-an-undefined-reference-unresolved-external-symbol-error-and-how-do-i-fix) do StackOverflow como referência teórica.

**Comment by calebepb** [comment]
Problema resolvido! :)
O `CMakeLists.txt` não inclui o `SquareRoot.cpp` como parte da compilação e, portanto, o `sqrtlib.cpp` e consequentemente o `sqrtlib.so` gerados não possuem o símbolo `_ZN10SquareRoot9calculateEd`(na verdade, esse símbolo é marcado como `undefined`na `vtable` - veja com `nm -C -u sqrtlib.so | grep calc`)
Minha sugestão é modificar a linha [18](https://github.com/LeoFuso/cpp_python_integration/blob/dev/cpp/CMakeLists.txt#L18), conforme abaixo:
```
add_library(sqrtlib SHARED sqrtlib.cpp SquareRoot.cpp)
```

Assim, o código em Python-3.6.5 abaixo funciona:
```
from sqrtlib import SquareRoot
sqrt = SquareRoot()
print(sqrt.calculate(4.0))
```

**Comment by LeoFuso** [comment]
Feito. Problema [resolvido](https://github.com/LeoFuso/cpp_python_integration/commit/567fdc57f57c13920bc11a7be46d098d64bab4ee). 

Já subi as modificações para a `branch` `dev`
